name: my first git hub actions

on:
 push:
   branches: main

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v5
        - name: my fisrt step
          run: |
             pwd
             date
             echo "This is fisrt repo"
             
        - name: check docker
          run: |
              docker -v
              docker ps
        - name: Checking nginx...
         run:
            systemctl status nginx

         
